[package]
name = "stormgate-process"
description = "Wine environment construction and process launching for Storm Gate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
stormgate-config.workspace = true
stormgate-graphics.workspace = true
stormgate-runtime.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
